/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiIntelligenceRouteImport } from './routes/ai-intelligence'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIntelligenceRoute = AiIntelligenceRouteImport.update({
  id: '/ai-intelligence',
  path: '/ai-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/alerts': typeof AlertsRoute
  '/matches': typeof MatchesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/alerts': typeof AlertsRoute
  '/matches': typeof MatchesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/alerts': typeof AlertsRoute
  '/matches': typeof MatchesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-intelligence' | '/alerts' | '/matches' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-intelligence' | '/alerts' | '/matches' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/ai-intelligence'
    | '/alerts'
    | '/matches'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiIntelligenceRoute: typeof AiIntelligenceRoute
  AlertsRoute: typeof AlertsRoute
  MatchesRoute: typeof MatchesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-intelligence': {
      id: '/ai-intelligence'
      path: '/ai-intelligence'
      fullPath: '/ai-intelligence'
      preLoaderRoute: typeof AiIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiIntelligenceRoute: AiIntelligenceRoute,
  AlertsRoute: AlertsRoute,
  MatchesRoute: MatchesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
